language: node_js
node_js:
  - node
sudo: false
before_script:
  - npm install -g gulp-cli
  - npm install -g bower
  - bower install
services:
  - xvfb
addons:
  firefox: 'latest'
script: npm run build && npm run test
deploy:
  provider: npm
  email: rthaut@gmail.com
  api_key:
    secure: Rn6tjq0oDDYnV+AYzu0mCwKUUwEGN8/+iNWfU8nwwF2VOgSRlkoL0BtJ+j5H0ZK4X7q4IydD8H2tMmkmqwt1cx6uFpNsvjgqO7WhadLfIgpZCe2M7++a6t9ZyZPZsk2p/lmj6o3u6MsSfyiA/Ux9RtuSGRXT7MTYlJafo4VSnlnUJmzhRTeM94h2XAMZZOucdPQGj/JahoB3LTBtHJLEzx8RaaFze12NAf2db8YyKTCK7wwdF57jS5B4jg4iOVMtlWDjVR0B4bKvwOUHiN+H+xTLaMOCSdrZS48Jo2Sb1LTvjyCWeHClw+HGDvMKgH3QXF8MWQzUdr4GdRqK2k+5Mv40F/hsElVCqrw8J0xi+a6NgL6swmqL0c9WdfQVIVfPOT3etnjAurwhhBERs1k4kJKPfwxItCRqixe5i/MWuPzSiIC+9Y+3ClacZLjUwqA4XEuyavdzPuUpadgGmWuV311RyHVRHkwvV43x6UC6VeGj6CddD3yF836JTxZz6x2yeTLMsnQdB5/8tEDRnmdrxpeL9qyEgVT6khnJcUUsxRy2yBsthO5qiYPU6duZ6SC0nXLHgGeVT0ZJaLJdVdyvfPaZvtOcQJfVfEcZx/XP0cI/u1GJGrBTg9wJkaTfDMmvHZdsnoDrWaogeqnOMq+FeILEwk6ws4zhKs7gTqmQ7Tc=
  on:
    tags: true
    repo: rthaut/angular-schema-form-panel
